-- SELECT_BASIC

-- ex1)

SELECT td.DEPARTMENT_NAME "학과 명 " , td.CATEGORY "계열"  FROM TB_DEPARTMENT td  ;


SELECT td.DEPARTMENT_NAME || ' 의 정원은 '  || td.CAPACITY || ' 명입니다'  FROM TB_DEPARTMENT td  ;

SELECT *  FROM TB_STUDENT ts   ;
SELECT * FROM TB_DEPARTMENT td ;

SELECT * FROM TB_DEPARTMENT td   ;
SELECT * FROM TB_STUDENT ts   ;

SELECT * FROM TB_DEPARTMENT td ;

SELECT * FROM TB_STUDENT ts;

--3번


SELECT *  FROM TB_STUDENT ts 
WHERE  ts.DEPARTMENT_NO='001' 
AND ts.ABSENCE_YN ='Y' 
AND SUBSTR(ts.STUDENT_SSN, 8,1)='2'   ; 

--AND TO_NUMBER(  SUBSTR(STUDENT_SSN,1, INSTR(STUDENT_SSN, '-' )-1 )) = 2 ;
 
-- WHERE TD.DEPARAMENT숫자가 001 + 여학생 + 휴학중



-- 4번
SELECT ts.STUDENT_NAME  FROM TB_STUDENT ts  WHERE ts.STUDENT_NO = 'A513079' OR ts.STUDENT_NO = 'A513090' OR ts.STUDENT_NO = 'A513091'
OR ts.STUDENT_NO = 'A513110' OR ts.STUDENT_NO = 'A513119';


-- 5번

SELECT td.DEPARTMENT_NAME, td.CATEGORY    FROM TB_DEPARTMENT td WHERE td.CAPACITY >=20 AND td.CAPACITY <=30 ;




-- 6번

SELECT tp.PROFESSOR_NAME  FROM TB_PROFESSOR tp  WHERE DEPARTMENT_NO IS NULL ; 


-- 7번

SELECT ts.STUDENT_NAME   FROM TB_STUDENT ts   WHERE DEPARTMENT_NO IS NULL ; 


-- 8번

SELECT tc.CLASS_NAME   FROM TB_CLASS tc    WHERE tc.PREATTENDING_CLASS_NO  IS NOT  NULL ; 

-- 9번
SELECT DISTINCT td.CATEGORY   FROM TB_DEPARTMENT td ; 


--10번

SELECT ts.STUDENT_NO, ts.STUDENT_NAME, ts.STUDENT_SSN FROM TB_STUDENT ts WHERE ( SUBSTR(STUDENT_ADDRESS, 1,2 )= '전주' AND SUBSTR(  TO_CHAR (ENTRANCE_DATE, 'YYYY/MM/DD') ,3,2)='02' ) ;



-- SELECT (Function파트)

-- ex1)

SELECT ts.STUDENT_NO, ts.STUDENT_NAME, ts.ENTRANCE_DATE  FROM TB_STUDENT ts WHERE DEPARTMENT_NO ='002' ORDER BY ENTRANCE_DATE   ;

-- ex2)

SELECT tp.PROFESSOR_NAME , tp.PROFESSOR_SSN   FROM TB_PROFESSOR tp  WHERE LENGTH(PROFESSOR_NAME)  <>3  ;
-- 컬럼 이름에는 COUNT가 아니라 LENGTH를 써야 함

-- ex3)
SELECT tp.PROFESSOR_NAME 교수이름 ,  125-SUBSTR(tp.PROFESSOR_SSN,1,2) 나이
FROM TB_PROFESSOR tp ORDER BY tp.PROFESSOR_SSN DESC   ;

-- ex4)

SELECT  SUBSTR(tp.PROFESSOR_NAME,2,2) 교수이름
FROM TB_PROFESSOR tp    ;


-- ex5)

SELECT ts.ENTRANCE_DATE - ts.STUDENT_SSN   FROM TB_STUDENT ts ;

SELECT TO_NUMBER(TO_CHAR(ts.ENTRANCE_DATE, 'YYYYMMDD' ))  , ts.STUDENT_NO , ts.STUDENT_NAME, SUBSTR(ts.STUDENT_SSN,1,2 ) 
FROM TB_STUDENT ts ;

--ex6)

-- ex7)

SELECT ts.STUDENT_NO, ts.STUDENT_NAME   FROM TB_STUDENT ts

WHERE TO_NUMBER(SUBSTR( TO_CHAR(ts.ENTRANCE_DATE, 'YYYYMMDD'),1,4 ))

-1900 -TO_NUMBER (SUBSTR(ts.STUDENT_SSN ,1,2))>19 ;


-- ex8)

-- 1900년대 1900년대 1900년대 2000년대

-- ex9)


SELECT SUM(tg.POINT) FROM TB_STUDENT ts  JOIN TB_GRADE tg  ON ts.STUDENT_NO  = tg.STUDENT_NO
WHERE tg.STUDENT_NO ='A517178';


-- ex10) 학과별 학생수를 구한다





-- ex11) 지도교수를 배정받지 못함

SELECT ts.STUDENT_NAME  FROM TB_STUDENT ts JOIN TB_PROFESSOR tp ON ts.DEPARTMENT_NO  = tp.DEPARTMENT_NO WHERE ts.COACH_PROFESSOR_NO IS NULL  ;



-- ex12) 학번이 A112113인 김고운 학생의 연도별 평점

SELECT ts.ENTRANCE_DATE 
FROM TB_STUDENT ts 
JOIN TB_GRADE tg  ON ts.STUDENT_NO = tg.STUDENT_NO 
WHERE ts.STUDENT_NO ='A112113'
GROUP BY ts.ENTRANCE_DATE  ;  

SELECT SUBSTR((tg.TERM_NO),1,4) FROM TB_GRADE tg ;

SELECT * FROM TB_STUDENT ts ;
SELECT * FROM TB_GRADE tg;
SELECT * FROM TB_CLASS_PROFESSOR tcp;
SELECT * FROM TB_PROFESSOR tP;
SELECT * FROM TB_CLASS tc;
SELECT * FROM TB_DEPARTMENT td;

